# Generated by Django 3.2.13 on 2022-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='business',
        ),
        migrations.RemoveField(
            model_name='category',
            name='entertainment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='general',
        ),
        migrations.RemoveField(
            model_name='category',
            name='health',
        ),
        migrations.RemoveField(
            model_name='category',
            name='science',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='category',
            name='technology',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
