# Generated by Django 3.2.13 on 2022-05-26 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220526_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=[], size=8),
        ),
    ]
