# Generated by Django 3.2.13 on 2022-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220526_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
