# Generated by Django 3.2.13 on 2022-06-03 09:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.TextField(null=True, verbose_name=users.models.Category),
        ),
    ]
