# Generated by Django 3.2.13 on 2022-06-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bkp_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
