# Generated by Django 3.2.13 on 2022-06-06 07:26

from django.db import migrations

def back_fill_user(apps, schema_editor):
    News = apps.get_model('news', 'News')
    for news in News.objects.all():
        news.bkp_category = news.category
        news.save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_bkp_category'),
    ]

    operations = [
        migrations.RunPython(
            back_fill_user,
        ),
    ]
