# Generated by Django 3.2.13 on 2022-06-07 06:55

from django.db import migrations

def back_fill_user(apps, schema_editor):
    News = apps.get_model('news', 'News')
    Category = apps.get_model('users', 'Category')

    a = Category.objects.values('name', 'id')
    
    for n in News.objects.values('bkp_category'):
        for i in range(0,len(a)):
            if n['bkp_category'] in a[i]['name']:
                new_category_id = a[i]['id']
                new_category_id.save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220606_0743'),
    ]

    operations = [
        migrations.RunPython(
            back_fill_user,
        ),
    ]
